config/routes.rb
Rails.application.routes.draw do
  resources :users 
  resources :candidates do
    member do
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :logs
  validates :name, presence: true
 def vote
  self.votes = self.votes + 1
   #inecrement(:votes) 擇一
  save
 end

end



#與helpers/user_helper.rb相比 通用型與此

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :candidate
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]
  # before_action :find_candidate, except: [:index, :new, :create]
  def index
    @candidates = Candidate.all
  end
  
  def new
    @candidate = Candidate.new
  end
  
  def show
    @candidate = Candidate.find_by(id: params[:id])
    end
  
  def vote
    log = Log.new(candidate: @candidate, ip_address: request.remote_ip)
    @candidate.logs << log
    @candidate.save
    redirect_to candidates_path, notice: "done!"
  end
  #def vote
  #  @candidate.vote
  #  redirect_to candidates_path, notice: "done!"
  #end
  
  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
    redirect_to candidates_path, notice: "success!"
    else
      render 'new'
      #redirect_to new_candidate_path
    end
    
    def edit
      end
    
    def update
    if @candidate.update(candidate_params)
    redirect_to candidates_path, notice: "updated!!"
    else
      render 'edit'
      #redirect_to new_candidate_path
    end
    end
    
    def destroy
      @candidate.destroy
      #flash[:notice] = "deleted!"
      redirect_to candidates_path, notice: "deleted!"
    end
end
  
  private
  def candidate_params
    params.require("candidate").permit(:name, :party, :age, :politics)
  end
  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
    redirect_to candidates_path, notice: "no data!!!" if @candidate.nil?
   end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def  display_name(candidate)
  "#{candidate.name}(#{candidate.party})"
end
end
#與models/candidate.rb 效果同 擇一即可
  #def  display_name(candidate)
  #"#{name}(#{party})"
  #end

app/views/candidates/_form.html.erb
<%= form_for candidate do |f| %>

name :<%= f.text_field :name %><br />
age :<%= f.text_field :age %><br />
party :<%= f.text_field :party %><br />
politics :<%= f.text_area :politics %><br />

<%= f.submit %>

<% end %>

app/views/candidates/edit.html.erb
<h1>
  Edit Candidate
</h1>
<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>Candidate List</h1>

<%= link_to "add candidate", new_candidate_path, class: "btn btn-success btn-xs" %>

<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <td></td>
    <td>Name</td>
    <td>Votes</td>
    <td>Age</td>
    <td>Politics</td>
    <td></td>
   </tr>
  </thead>
  
  <tbody>
  <% @candidates.each do |candidate| %>
  <tr>
    <td><%= link_to "vote!", vote_candidate_path(candidate), class: "btn btn-xs btn-danger", data: { confirm: "Vote this one?!" }, method: "post" %></td>
    <td><%= link_to display_name(candidate), candidate %></td>
    <td><%= candidate.logs.count %></td>
    <td><%= candidate.age %></td>
    <td><%= candidate.politics %></td>
    <td>
     <%= link_to "edit", edit_candidate_path(candidate), class: "btn btn-success btn-xs"  %>
     <%= link_to "delete", candidate, method: "delete", data: { confirm: 'delete?!'}, class: "btn btn-danger btn-xs"  %>
    </td>
  </tr>
    <% end %>
  </tbody>
</table>




<ul>
 <% @candidates.each do |candidate| %>
<li>
  <%= link_to candidate.name, candidate %>
  <%= link_to "edit", edit_candidate_path(candidate) %>
  <%= link_to "delete", candidate, method: "delete", data: { confirm: 'delete?!'} %>
  </li>
  
  
  <% end %>
</ul>

app/views/candidates/new.html.erb
<h1>
  New Candidate
</h1>
<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<h1>
  <%= @candidate.name %>
</h1>
age: <%= @candidate.age %>

<br />
<%= link_to "back", candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HolyPal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
    <h3><%= notice %> </h3>
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>